// End-to-end check for Phase 4: stream a real recorded "Astraa" clip over
// WebSocket through the full server + VAD + wake-word pipeline and require the
// exact events the Python reference produced (testdata/e2e_ww_golden.json,
// generated by astra_ml.export.golden_ww after training).
package tests

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"net/http/httptest"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/coder/websocket"
	"google.golang.org/protobuf/proto"

	"github.com/arnav/astra/services/backend/internal/pb"
	"github.com/arnav/astra/services/backend/internal/server"
	"github.com/arnav/astra/services/backend/internal/vad"
	"github.com/arnav/astra/services/backend/internal/wakeword"
)

func TestEndToEndWakeWord(t *testing.T) {
	data, err := os.ReadFile("testdata/e2e_ww_golden.json")
	if os.IsNotExist(err) {
		t.Skip("e2e_ww_golden.json not generated yet (needs trained ww_v1 + recordings)")
	}
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat("../../../assets/models/wakeword/ww_v1.onnx"); os.IsNotExist(err) {
		t.Skip("ww_v1.onnx not committed yet")
	}
	if err := vad.Init(""); err != nil {
		t.Skipf("onnxruntime unavailable: %v", err)
	}

	var golden struct {
		PCM        string   `json:"pcm_s16le_base64"`
		VadEvents  [][2]any `json:"vad_events"`
		WakeFrames []int    `json:"wake_frames"`
	}
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatal(err)
	}
	pcm, err := base64.StdEncoding.DecodeString(golden.PCM)
	if err != nil {
		t.Fatal(err)
	}

	vadCfg, err := vad.LoadConfig("../../../assets/models/vad/vad_v1.json")
	if err != nil {
		t.Fatal(err)
	}
	vadEngine, err := vad.NewEngine("../../../assets/models/vad/vad_v1.onnx", vadCfg)
	if err != nil {
		t.Fatal(err)
	}
	defer vadEngine.Close()
	wwCfg, err := wakeword.LoadConfig("../../../assets/models/wakeword/ww_v1.json")
	if err != nil {
		t.Fatal(err)
	}
	wwEngine, err := wakeword.NewEngine("../../../assets/models/wakeword/ww_v1.onnx", wwCfg)
	if err != nil {
		t.Fatal(err)
	}
	defer wwEngine.Close()

	var mu sync.Mutex
	var vadEvents []vad.Event
	var wakes []wakeword.Event
	var sink server.Sink
	srv := server.New()
	srv.NewSink = func(streamID string) server.Sink {
		sink = wakeword.NewSink(streamID, vadEngine, vadCfg, wwEngine, wwCfg,
			func(e vad.Event) {
				mu.Lock()
				vadEvents = append(vadEvents, e)
				mu.Unlock()
			},
			func(e wakeword.Event) {
				mu.Lock()
				wakes = append(wakes, e)
				mu.Unlock()
			}, nil)
		return sink
	}

	ts := httptest.NewServer(srv)
	defer ts.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	conn, _, err := websocket.Dial(ctx, strings.Replace(ts.URL, "http", "ws", 1), nil)
	if err != nil {
		t.Fatal(err)
	}

	send := func(msg *pb.ClientMessage) {
		t.Helper()
		raw, err := proto.Marshal(msg)
		if err != nil {
			t.Fatal(err)
		}
		if err := conn.Write(ctx, websocket.MessageBinary, raw); err != nil {
			t.Fatal(err)
		}
	}

	send(&pb.ClientMessage{Msg: &pb.ClientMessage_StreamStart{StreamStart: &pb.StreamStart{
		SampleRateHz: 16000, Channels: 1, BitsPerSample: 16, FrameDurationMs: 20,
	}}})
	if _, _, err := conn.Read(ctx); err != nil {
		t.Fatal(err)
	}

	for seq := uint64(0); int(seq)*frameBytes < len(pcm); seq++ {
		off := int(seq) * frameBytes
		send(&pb.ClientMessage{Msg: &pb.ClientMessage_AudioFrame{AudioFrame: &pb.AudioFrame{
			Seq: seq, Pcm: pcm[off : off+frameBytes],
		}}})
	}
	send(&pb.ClientMessage{Msg: &pb.ClientMessage_StreamStop{StreamStop: &pb.StreamStop{}}})
	conn.Close(websocket.StatusNormalClosure, "")

	sink.Wait()
	if err := sink.Err(); err != nil {
		t.Fatalf("sink failed: %v", err)
	}

	mu.Lock()
	defer mu.Unlock()
	if len(vadEvents) != len(golden.VadEvents) {
		t.Fatalf("vad events: got %v, want %v", vadEvents, golden.VadEvents)
	}
	for i, w := range golden.VadEvents {
		kind, frame := w[0].(string), int(w[1].(float64))
		if string(vadEvents[i].Type) != kind || vadEvents[i].Frame != frame {
			t.Fatalf("vad event %d: got %v, want (%s, %d)", i, vadEvents[i], kind, frame)
		}
	}
	if len(wakes) != len(golden.WakeFrames) {
		t.Fatalf("wakes: got %v, want %v", wakes, golden.WakeFrames)
	}
	for i, want := range golden.WakeFrames {
		if wakes[i].Frame != want {
			t.Fatalf("wake %d: frame %d, want %d", i, wakes[i].Frame, want)
		}
	}
}
