# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astra/v1/asr.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'astra/v1/asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61stra/v1/asr.proto\x12\x08\x61stra.v1\"o\n\x11TranscribeRequest\x12(\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x16.astra.v1.StreamConfigH\x00\x12%\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x14.astra.v1.AudioChunkH\x00\x42\t\n\x07payload\"\x88\x01\n\x0cStreamConfig\x12\x14\n\x0cutterance_id\x18\x01 \x01(\x04\x12\x16\n\x0esample_rate_hz\x18\x02 \x01(\r\x12\x10\n\x08\x63hannels\x18\x03 \x01(\r\x12\x17\n\x0f\x62its_per_sample\x18\x04 \x01(\r\x12\r\n\x05model\x18\x05 \x01(\t\x12\x10\n\x08language\x18\x06 \x01(\t\"\x19\n\nAudioChunk\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\"4\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x32X\n\x03\x41SR\x12Q\n\x10StreamTranscribe\x12\x1b.astra.v1.TranscribeRequest\x1a\x1c.astra.v1.TranscribeResponse(\x01\x30\x01\x42\x39Z7github.com/arnav/astra/services/backend/internal/asr/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astra.v1.asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/arnav/astra/services/backend/internal/asr/pb'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=32
  _globals['_TRANSCRIBEREQUEST']._serialized_end=143
  _globals['_STREAMCONFIG']._serialized_start=146
  _globals['_STREAMCONFIG']._serialized_end=282
  _globals['_AUDIOCHUNK']._serialized_start=284
  _globals['_AUDIOCHUNK']._serialized_end=309
  _globals['_TRANSCRIBERESPONSE']._serialized_start=311
  _globals['_TRANSCRIBERESPONSE']._serialized_end=363
  _globals['_ASR']._serialized_start=365
  _globals['_ASR']._serialized_end=453
# @@protoc_insertion_point(module_scope)
