// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: astra/v1/astra.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplyEnd_Reason int32

const (
	ReplyEnd_REASON_UNSPECIFIED ReplyEnd_Reason = 0
	ReplyEnd_DONE               ReplyEnd_Reason = 1 // the reply finished on its own
	ReplyEnd_BARGED_IN          ReplyEnd_Reason = 2 // the user talked over it; a Cancel preceded this
	ReplyEnd_ERROR              ReplyEnd_Reason = 3 // LLM or TTS failed; the stream survives
)

// Enum value maps for ReplyEnd_Reason.
var (
	ReplyEnd_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "DONE",
		2: "BARGED_IN",
		3: "ERROR",
	}
	ReplyEnd_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"DONE":               1,
		"BARGED_IN":          2,
		"ERROR":              3,
	}
)

func (x ReplyEnd_Reason) Enum() *ReplyEnd_Reason {
	p := new(ReplyEnd_Reason)
	*p = x
	return p
}

func (x ReplyEnd_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplyEnd_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_astra_v1_astra_proto_enumTypes[0].Descriptor()
}

func (ReplyEnd_Reason) Type() protoreflect.EnumType {
	return &file_astra_v1_astra_proto_enumTypes[0]
}

func (x ReplyEnd_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplyEnd_Reason.Descriptor instead.
func (ReplyEnd_Reason) EnumDescriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{13, 0}
}

// Client -> server envelope. Exactly one StreamStart per connection,
// then AudioFrames in seq order, then an optional StreamStop.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_StreamStart
	//	*ClientMessage_AudioFrame
	//	*ClientMessage_StreamStop
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_astra_v1_astra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetStreamStart() *StreamStart {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_StreamStart); ok {
			return x.StreamStart
		}
	}
	return nil
}

func (x *ClientMessage) GetAudioFrame() *AudioFrame {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_AudioFrame); ok {
			return x.AudioFrame
		}
	}
	return nil
}

func (x *ClientMessage) GetStreamStop() *StreamStop {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_StreamStop); ok {
			return x.StreamStop
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_StreamStart struct {
	StreamStart *StreamStart `protobuf:"bytes,1,opt,name=stream_start,json=streamStart,proto3,oneof"`
}

type ClientMessage_AudioFrame struct {
	AudioFrame *AudioFrame `protobuf:"bytes,2,opt,name=audio_frame,json=audioFrame,proto3,oneof"`
}

type ClientMessage_StreamStop struct {
	StreamStop *StreamStop `protobuf:"bytes,3,opt,name=stream_stop,json=streamStop,proto3,oneof"`
}

func (*ClientMessage_StreamStart) isClientMessage_Msg() {}

func (*ClientMessage_AudioFrame) isClientMessage_Msg() {}

func (*ClientMessage_StreamStop) isClientMessage_Msg() {}

// Declares the audio format for the Stream. The server accepts exactly
// 16000 Hz / 1 channel / 16-bit signed LE PCM / 20 ms frames and rejects
// anything else — fields exist for validation, not negotiation.
type StreamStart struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SampleRateHz    uint32                 `protobuf:"varint,1,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	Channels        uint32                 `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	BitsPerSample   uint32                 `protobuf:"varint,3,opt,name=bits_per_sample,json=bitsPerSample,proto3" json:"bits_per_sample,omitempty"`
	FrameDurationMs uint32                 `protobuf:"varint,4,opt,name=frame_duration_ms,json=frameDurationMs,proto3" json:"frame_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamStart) Reset() {
	*x = StreamStart{}
	mi := &file_astra_v1_astra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStart) ProtoMessage() {}

func (x *StreamStart) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStart.ProtoReflect.Descriptor instead.
func (*StreamStart) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{1}
}

func (x *StreamStart) GetSampleRateHz() uint32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *StreamStart) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *StreamStart) GetBitsPerSample() uint32 {
	if x != nil {
		return x.BitsPerSample
	}
	return 0
}

func (x *StreamStart) GetFrameDurationMs() uint32 {
	if x != nil {
		return x.FrameDurationMs
	}
	return 0
}

// One Frame of PCM audio. pcm must be exactly 640 bytes
// (320 samples of s16le at 16 kHz = 20 ms).
type AudioFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // starts at 0, increments by 1 per frame
	Pcm           []byte                 `protobuf:"bytes,2,opt,name=pcm,proto3" json:"pcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_astra_v1_astra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{2}
}

func (x *AudioFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AudioFrame) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

type StreamStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStop) Reset() {
	*x = StreamStop{}
	mi := &file_astra_v1_astra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStop) ProtoMessage() {}

func (x *StreamStop) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStop.ProtoReflect.Descriptor instead.
func (*StreamStop) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{3}
}

// Server -> client envelope. StreamStarted is sent once; the reply messages
// stream per turn. Every reply message carries the utterance_id it belongs to
// (the utterance's first frame seq) so a client can discard audio from a turn
// it has already cancelled.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_StreamStarted
	//	*ServerMessage_Error
	//	*ServerMessage_Transcript
	//	*ServerMessage_ReplyDelta
	//	*ServerMessage_ReplyAudio
	//	*ServerMessage_ReplyEnd
	//	*ServerMessage_Cancel
	//	*ServerMessage_Turn
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_astra_v1_astra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetStreamStarted() *StreamStarted {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_StreamStarted); ok {
			return x.StreamStarted
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMessage) GetTranscript() *Transcript {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Transcript); ok {
			return x.Transcript
		}
	}
	return nil
}

func (x *ServerMessage) GetReplyDelta() *ReplyDelta {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ReplyDelta); ok {
			return x.ReplyDelta
		}
	}
	return nil
}

func (x *ServerMessage) GetReplyAudio() *ReplyAudio {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ReplyAudio); ok {
			return x.ReplyAudio
		}
	}
	return nil
}

func (x *ServerMessage) GetReplyEnd() *ReplyEnd {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ReplyEnd); ok {
			return x.ReplyEnd
		}
	}
	return nil
}

func (x *ServerMessage) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ServerMessage) GetTurn() *Turn {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Turn); ok {
			return x.Turn
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_StreamStarted struct {
	StreamStarted *StreamStarted `protobuf:"bytes,1,opt,name=stream_started,json=streamStarted,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ServerMessage_Transcript struct {
	Transcript *Transcript `protobuf:"bytes,3,opt,name=transcript,proto3,oneof"`
}

type ServerMessage_ReplyDelta struct {
	ReplyDelta *ReplyDelta `protobuf:"bytes,4,opt,name=reply_delta,json=replyDelta,proto3,oneof"`
}

type ServerMessage_ReplyAudio struct {
	ReplyAudio *ReplyAudio `protobuf:"bytes,5,opt,name=reply_audio,json=replyAudio,proto3,oneof"`
}

type ServerMessage_ReplyEnd struct {
	ReplyEnd *ReplyEnd `protobuf:"bytes,6,opt,name=reply_end,json=replyEnd,proto3,oneof"`
}

type ServerMessage_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,7,opt,name=cancel,proto3,oneof"`
}

type ServerMessage_Turn struct {
	Turn *Turn `protobuf:"bytes,8,opt,name=turn,proto3,oneof"`
}

func (*ServerMessage_StreamStarted) isServerMessage_Msg() {}

func (*ServerMessage_Error) isServerMessage_Msg() {}

func (*ServerMessage_Transcript) isServerMessage_Msg() {}

func (*ServerMessage_ReplyDelta) isServerMessage_Msg() {}

func (*ServerMessage_ReplyAudio) isServerMessage_Msg() {}

func (*ServerMessage_ReplyEnd) isServerMessage_Msg() {}

func (*ServerMessage_Cancel) isServerMessage_Msg() {}

func (*ServerMessage_Turn) isServerMessage_Msg() {}

type StreamStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStarted) Reset() {
	*x = StreamStarted{}
	mi := &file_astra_v1_astra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStarted) ProtoMessage() {}

func (x *StreamStarted) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStarted.ProtoReflect.Descriptor instead.
func (*StreamStarted) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{5}
}

func (x *StreamStarted) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// Sent once on any protocol violation; the connection closes after.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_astra_v1_astra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// What the user said, once the utterance closed and ASR returned.
type Transcript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   uint64                 `protobuf:"varint,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"` // seq of the utterance's first frame
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // NEW: true for final transcript, false for partial
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcript) Reset() {
	*x = Transcript{}
	mi := &file_astra_v1_astra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcript) ProtoMessage() {}

func (x *Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcript.ProtoReflect.Descriptor instead.
func (*Transcript) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{7}
}

func (x *Transcript) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

func (x *Transcript) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transcript) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// One chunk of the assistant's reply text, as the LLM streams it. Display
// only — the audio path is independent and may lag behind.
type ReplyDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   uint64                 `protobuf:"varint,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyDelta) Reset() {
	*x = ReplyDelta{}
	mi := &file_astra_v1_astra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyDelta) ProtoMessage() {}

func (x *ReplyDelta) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyDelta.ProtoReflect.Descriptor instead.
func (*ReplyDelta) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyDelta) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

func (x *ReplyDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// One chunk of synthesized reply audio: mono s16le. seq starts at 0 per turn.
//
// Unlike the inbound AudioFrame this is NOT pinned to 16 kHz. The server only
// forwards reply audio — nothing server-side analyses it — so pinning the rate
// would mean writing a resampler purely to satisfy a constant. The TTS
// provider's rate is carried here instead and the client resamples on
// playback, which the Web Audio API does natively.
type ReplyAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   uint64                 `protobuf:"varint,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Pcm           []byte                 `protobuf:"bytes,3,opt,name=pcm,proto3" json:"pcm,omitempty"`
	SampleRateHz  uint32                 `protobuf:"varint,4,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyAudio) Reset() {
	*x = ReplyAudio{}
	mi := &file_astra_v1_astra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyAudio) ProtoMessage() {}

func (x *ReplyAudio) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyAudio.ProtoReflect.Descriptor instead.
func (*ReplyAudio) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{9}
}

func (x *ReplyAudio) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

func (x *ReplyAudio) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReplyAudio) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

func (x *ReplyAudio) GetSampleRateHz() uint32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

// Discard any buffered audio for this turn NOW. Sent on barge-in, ahead of
// ReplyEnd: stopping the server from sending is not the same as stopping the
// client from playing what it already holds, and the client-side flush is what
// the user actually perceives as the interruption.
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   uint64                 `protobuf:"varint,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_astra_v1_astra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{10}
}

func (x *Cancel) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

// One measured stage of a latency chain. start_ms is relative to the chain's
// T0, so a client draws a waterfall straight from these two numbers.
type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartMs       uint32                 `protobuf:"varint,2,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	DurMs         uint32                 `protobuf:"varint,3,opt,name=dur_ms,json=durMs,proto3" json:"dur_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_astra_v1_astra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{11}
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetStartMs() uint32 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *Span) GetDurMs() uint32 {
	if x != nil {
		return x.DurMs
	}
	return 0
}

// The latency breakdown of one chain, sent as soon as the chain completes —
// for a turn that is the first ReplyAudio, not ReplyEnd, since a long reply
// would otherwise delay the numbers far past the moment they describe.
//
// Every boundary is stamped server-side. The turn chain therefore ends at the
// first reply audio *written to the socket*: what the client does after that
// (decode, schedule, play) is on the client's clock and is not measured here.
type Turn struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId uint64                 `protobuf:"varint,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Chain       string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"` // "turn" or "barge"
	Spans       []*Span                `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans,omitempty"`
	// Time to first audio, excluding how long the user spoke. Turn chain only.
	HeadlineMs    uint32 `protobuf:"varint,4,opt,name=headline_ms,json=headlineMs,proto3" json:"headline_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_astra_v1_astra_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{12}
}

func (x *Turn) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

func (x *Turn) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Turn) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *Turn) GetHeadlineMs() uint32 {
	if x != nil {
		return x.HeadlineMs
	}
	return 0
}

// Terminates a turn. Exactly one per turn that produced any reply.
type ReplyEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   uint64                 `protobuf:"varint,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	Reason        ReplyEnd_Reason        `protobuf:"varint,2,opt,name=reason,proto3,enum=astra.v1.ReplyEnd_Reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyEnd) Reset() {
	*x = ReplyEnd{}
	mi := &file_astra_v1_astra_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyEnd) ProtoMessage() {}

func (x *ReplyEnd) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyEnd.ProtoReflect.Descriptor instead.
func (*ReplyEnd) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyEnd) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

func (x *ReplyEnd) GetReason() ReplyEnd_Reason {
	if x != nil {
		return x.Reason
	}
	return ReplyEnd_REASON_UNSPECIFIED
}

var File_astra_v1_astra_proto protoreflect.FileDescriptor

const file_astra_v1_astra_proto_rawDesc = "" +
	"\n" +
	"\x14astra/v1/astra.proto\x12\bastra.v1\"\xc4\x01\n" +
	"\rClientMessage\x12:\n" +
	"\fstream_start\x18\x01 \x01(\v2\x15.astra.v1.StreamStartH\x00R\vstreamStart\x127\n" +
	"\vaudio_frame\x18\x02 \x01(\v2\x14.astra.v1.AudioFrameH\x00R\n" +
	"audioFrame\x127\n" +
	"\vstream_stop\x18\x03 \x01(\v2\x14.astra.v1.StreamStopH\x00R\n" +
	"streamStopB\x05\n" +
	"\x03msg\"\xa3\x01\n" +
	"\vStreamStart\x12$\n" +
	"\x0esample_rate_hz\x18\x01 \x01(\rR\fsampleRateHz\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\rR\bchannels\x12&\n" +
	"\x0fbits_per_sample\x18\x03 \x01(\rR\rbitsPerSample\x12*\n" +
	"\x11frame_duration_ms\x18\x04 \x01(\rR\x0fframeDurationMs\"0\n" +
	"\n" +
	"AudioFrame\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03pcm\x18\x02 \x01(\fR\x03pcm\"\f\n" +
	"\n" +
	"StreamStop\"\xb0\x03\n" +
	"\rServerMessage\x12@\n" +
	"\x0estream_started\x18\x01 \x01(\v2\x17.astra.v1.StreamStartedH\x00R\rstreamStarted\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.astra.v1.ErrorH\x00R\x05error\x126\n" +
	"\n" +
	"transcript\x18\x03 \x01(\v2\x14.astra.v1.TranscriptH\x00R\n" +
	"transcript\x127\n" +
	"\vreply_delta\x18\x04 \x01(\v2\x14.astra.v1.ReplyDeltaH\x00R\n" +
	"replyDelta\x127\n" +
	"\vreply_audio\x18\x05 \x01(\v2\x14.astra.v1.ReplyAudioH\x00R\n" +
	"replyAudio\x121\n" +
	"\treply_end\x18\x06 \x01(\v2\x12.astra.v1.ReplyEndH\x00R\breplyEnd\x12*\n" +
	"\x06cancel\x18\a \x01(\v2\x10.astra.v1.CancelH\x00R\x06cancel\x12$\n" +
	"\x04turn\x18\b \x01(\v2\x0e.astra.v1.TurnH\x00R\x04turnB\x05\n" +
	"\x03msg\",\n" +
	"\rStreamStarted\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"^\n" +
	"\n" +
	"Transcript\x12!\n" +
	"\futterance_id\x18\x01 \x01(\x04R\vutteranceId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\"C\n" +
	"\n" +
	"ReplyDelta\x12!\n" +
	"\futterance_id\x18\x01 \x01(\x04R\vutteranceId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"y\n" +
	"\n" +
	"ReplyAudio\x12!\n" +
	"\futterance_id\x18\x01 \x01(\x04R\vutteranceId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03pcm\x18\x03 \x01(\fR\x03pcm\x12$\n" +
	"\x0esample_rate_hz\x18\x04 \x01(\rR\fsampleRateHz\"+\n" +
	"\x06Cancel\x12!\n" +
	"\futterance_id\x18\x01 \x01(\x04R\vutteranceId\"L\n" +
	"\x04Span\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bstart_ms\x18\x02 \x01(\rR\astartMs\x12\x15\n" +
	"\x06dur_ms\x18\x03 \x01(\rR\x05durMs\"\x86\x01\n" +
	"\x04Turn\x12!\n" +
	"\futterance_id\x18\x01 \x01(\x04R\vutteranceId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12$\n" +
	"\x05spans\x18\x03 \x03(\v2\x0e.astra.v1.SpanR\x05spans\x12\x1f\n" +
	"\vheadline_ms\x18\x04 \x01(\rR\n" +
	"headlineMs\"\xa6\x01\n" +
	"\bReplyEnd\x12!\n" +
	"\futterance_id\x18\x01 \x01(\x04R\vutteranceId\x121\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x19.astra.v1.ReplyEnd.ReasonR\x06reason\"D\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04DONE\x10\x01\x12\r\n" +
	"\tBARGED_IN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03B5Z3github.com/arnav/astra/services/backend/internal/pbb\x06proto3"

var (
	file_astra_v1_astra_proto_rawDescOnce sync.Once
	file_astra_v1_astra_proto_rawDescData []byte
)

func file_astra_v1_astra_proto_rawDescGZIP() []byte {
	file_astra_v1_astra_proto_rawDescOnce.Do(func() {
		file_astra_v1_astra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astra_v1_astra_proto_rawDesc), len(file_astra_v1_astra_proto_rawDesc)))
	})
	return file_astra_v1_astra_proto_rawDescData
}

var file_astra_v1_astra_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_astra_v1_astra_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_astra_v1_astra_proto_goTypes = []any{
	(ReplyEnd_Reason)(0),  // 0: astra.v1.ReplyEnd.Reason
	(*ClientMessage)(nil), // 1: astra.v1.ClientMessage
	(*StreamStart)(nil),   // 2: astra.v1.StreamStart
	(*AudioFrame)(nil),    // 3: astra.v1.AudioFrame
	(*StreamStop)(nil),    // 4: astra.v1.StreamStop
	(*ServerMessage)(nil), // 5: astra.v1.ServerMessage
	(*StreamStarted)(nil), // 6: astra.v1.StreamStarted
	(*Error)(nil),         // 7: astra.v1.Error
	(*Transcript)(nil),    // 8: astra.v1.Transcript
	(*ReplyDelta)(nil),    // 9: astra.v1.ReplyDelta
	(*ReplyAudio)(nil),    // 10: astra.v1.ReplyAudio
	(*Cancel)(nil),        // 11: astra.v1.Cancel
	(*Span)(nil),          // 12: astra.v1.Span
	(*Turn)(nil),          // 13: astra.v1.Turn
	(*ReplyEnd)(nil),      // 14: astra.v1.ReplyEnd
}
var file_astra_v1_astra_proto_depIdxs = []int32{
	2,  // 0: astra.v1.ClientMessage.stream_start:type_name -> astra.v1.StreamStart
	3,  // 1: astra.v1.ClientMessage.audio_frame:type_name -> astra.v1.AudioFrame
	4,  // 2: astra.v1.ClientMessage.stream_stop:type_name -> astra.v1.StreamStop
	6,  // 3: astra.v1.ServerMessage.stream_started:type_name -> astra.v1.StreamStarted
	7,  // 4: astra.v1.ServerMessage.error:type_name -> astra.v1.Error
	8,  // 5: astra.v1.ServerMessage.transcript:type_name -> astra.v1.Transcript
	9,  // 6: astra.v1.ServerMessage.reply_delta:type_name -> astra.v1.ReplyDelta
	10, // 7: astra.v1.ServerMessage.reply_audio:type_name -> astra.v1.ReplyAudio
	14, // 8: astra.v1.ServerMessage.reply_end:type_name -> astra.v1.ReplyEnd
	11, // 9: astra.v1.ServerMessage.cancel:type_name -> astra.v1.Cancel
	13, // 10: astra.v1.ServerMessage.turn:type_name -> astra.v1.Turn
	12, // 11: astra.v1.Turn.spans:type_name -> astra.v1.Span
	0,  // 12: astra.v1.ReplyEnd.reason:type_name -> astra.v1.ReplyEnd.Reason
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_astra_v1_astra_proto_init() }
func file_astra_v1_astra_proto_init() {
	if File_astra_v1_astra_proto != nil {
		return
	}
	file_astra_v1_astra_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_StreamStart)(nil),
		(*ClientMessage_AudioFrame)(nil),
		(*ClientMessage_StreamStop)(nil),
	}
	file_astra_v1_astra_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_StreamStarted)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_Transcript)(nil),
		(*ServerMessage_ReplyDelta)(nil),
		(*ServerMessage_ReplyAudio)(nil),
		(*ServerMessage_ReplyEnd)(nil),
		(*ServerMessage_Cancel)(nil),
		(*ServerMessage_Turn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astra_v1_astra_proto_rawDesc), len(file_astra_v1_astra_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_astra_v1_astra_proto_goTypes,
		DependencyIndexes: file_astra_v1_astra_proto_depIdxs,
		EnumInfos:         file_astra_v1_astra_proto_enumTypes,
		MessageInfos:      file_astra_v1_astra_proto_msgTypes,
	}.Build()
	File_astra_v1_astra_proto = out.File
	file_astra_v1_astra_proto_goTypes = nil
	file_astra_v1_astra_proto_depIdxs = nil
}
