// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: astra/v1/astra.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client -> server envelope. Exactly one StreamStart per connection,
// then AudioFrames in seq order, then an optional StreamStop.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_StreamStart
	//	*ClientMessage_AudioFrame
	//	*ClientMessage_StreamStop
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_astra_v1_astra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetStreamStart() *StreamStart {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_StreamStart); ok {
			return x.StreamStart
		}
	}
	return nil
}

func (x *ClientMessage) GetAudioFrame() *AudioFrame {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_AudioFrame); ok {
			return x.AudioFrame
		}
	}
	return nil
}

func (x *ClientMessage) GetStreamStop() *StreamStop {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_StreamStop); ok {
			return x.StreamStop
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_StreamStart struct {
	StreamStart *StreamStart `protobuf:"bytes,1,opt,name=stream_start,json=streamStart,proto3,oneof"`
}

type ClientMessage_AudioFrame struct {
	AudioFrame *AudioFrame `protobuf:"bytes,2,opt,name=audio_frame,json=audioFrame,proto3,oneof"`
}

type ClientMessage_StreamStop struct {
	StreamStop *StreamStop `protobuf:"bytes,3,opt,name=stream_stop,json=streamStop,proto3,oneof"`
}

func (*ClientMessage_StreamStart) isClientMessage_Msg() {}

func (*ClientMessage_AudioFrame) isClientMessage_Msg() {}

func (*ClientMessage_StreamStop) isClientMessage_Msg() {}

// Declares the audio format for the Stream. The server accepts exactly
// 16000 Hz / 1 channel / 16-bit signed LE PCM / 20 ms frames and rejects
// anything else — fields exist for validation, not negotiation.
type StreamStart struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SampleRateHz    uint32                 `protobuf:"varint,1,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	Channels        uint32                 `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	BitsPerSample   uint32                 `protobuf:"varint,3,opt,name=bits_per_sample,json=bitsPerSample,proto3" json:"bits_per_sample,omitempty"`
	FrameDurationMs uint32                 `protobuf:"varint,4,opt,name=frame_duration_ms,json=frameDurationMs,proto3" json:"frame_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamStart) Reset() {
	*x = StreamStart{}
	mi := &file_astra_v1_astra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStart) ProtoMessage() {}

func (x *StreamStart) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStart.ProtoReflect.Descriptor instead.
func (*StreamStart) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{1}
}

func (x *StreamStart) GetSampleRateHz() uint32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *StreamStart) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *StreamStart) GetBitsPerSample() uint32 {
	if x != nil {
		return x.BitsPerSample
	}
	return 0
}

func (x *StreamStart) GetFrameDurationMs() uint32 {
	if x != nil {
		return x.FrameDurationMs
	}
	return 0
}

// One Frame of PCM audio. pcm must be exactly 640 bytes
// (320 samples of s16le at 16 kHz = 20 ms).
type AudioFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // starts at 0, increments by 1 per frame
	Pcm           []byte                 `protobuf:"bytes,2,opt,name=pcm,proto3" json:"pcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_astra_v1_astra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{2}
}

func (x *AudioFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AudioFrame) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

type StreamStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStop) Reset() {
	*x = StreamStop{}
	mi := &file_astra_v1_astra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStop) ProtoMessage() {}

func (x *StreamStop) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStop.ProtoReflect.Descriptor instead.
func (*StreamStop) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{3}
}

// Server -> client envelope.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_StreamStarted
	//	*ServerMessage_Error
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_astra_v1_astra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetStreamStarted() *StreamStarted {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_StreamStarted); ok {
			return x.StreamStarted
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_StreamStarted struct {
	StreamStarted *StreamStarted `protobuf:"bytes,1,opt,name=stream_started,json=streamStarted,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_StreamStarted) isServerMessage_Msg() {}

func (*ServerMessage_Error) isServerMessage_Msg() {}

type StreamStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStarted) Reset() {
	*x = StreamStarted{}
	mi := &file_astra_v1_astra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStarted) ProtoMessage() {}

func (x *StreamStarted) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStarted.ProtoReflect.Descriptor instead.
func (*StreamStarted) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{5}
}

func (x *StreamStarted) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// Sent once on any protocol violation; the connection closes after.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_astra_v1_astra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_astra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_astra_v1_astra_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_astra_v1_astra_proto protoreflect.FileDescriptor

const file_astra_v1_astra_proto_rawDesc = "" +
	"\n" +
	"\x14astra/v1/astra.proto\x12\bastra.v1\"\xc4\x01\n" +
	"\rClientMessage\x12:\n" +
	"\fstream_start\x18\x01 \x01(\v2\x15.astra.v1.StreamStartH\x00R\vstreamStart\x127\n" +
	"\vaudio_frame\x18\x02 \x01(\v2\x14.astra.v1.AudioFrameH\x00R\n" +
	"audioFrame\x127\n" +
	"\vstream_stop\x18\x03 \x01(\v2\x14.astra.v1.StreamStopH\x00R\n" +
	"streamStopB\x05\n" +
	"\x03msg\"\xa3\x01\n" +
	"\vStreamStart\x12$\n" +
	"\x0esample_rate_hz\x18\x01 \x01(\rR\fsampleRateHz\x12\x1a\n" +
	"\bchannels\x18\x02 \x01(\rR\bchannels\x12&\n" +
	"\x0fbits_per_sample\x18\x03 \x01(\rR\rbitsPerSample\x12*\n" +
	"\x11frame_duration_ms\x18\x04 \x01(\rR\x0fframeDurationMs\"0\n" +
	"\n" +
	"AudioFrame\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03pcm\x18\x02 \x01(\fR\x03pcm\"\f\n" +
	"\n" +
	"StreamStop\"\x81\x01\n" +
	"\rServerMessage\x12@\n" +
	"\x0estream_started\x18\x01 \x01(\v2\x17.astra.v1.StreamStartedH\x00R\rstreamStarted\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.astra.v1.ErrorH\x00R\x05errorB\x05\n" +
	"\x03msg\",\n" +
	"\rStreamStarted\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB5Z3github.com/arnav/astra/services/backend/internal/pbb\x06proto3"

var (
	file_astra_v1_astra_proto_rawDescOnce sync.Once
	file_astra_v1_astra_proto_rawDescData []byte
)

func file_astra_v1_astra_proto_rawDescGZIP() []byte {
	file_astra_v1_astra_proto_rawDescOnce.Do(func() {
		file_astra_v1_astra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astra_v1_astra_proto_rawDesc), len(file_astra_v1_astra_proto_rawDesc)))
	})
	return file_astra_v1_astra_proto_rawDescData
}

var file_astra_v1_astra_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_astra_v1_astra_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: astra.v1.ClientMessage
	(*StreamStart)(nil),   // 1: astra.v1.StreamStart
	(*AudioFrame)(nil),    // 2: astra.v1.AudioFrame
	(*StreamStop)(nil),    // 3: astra.v1.StreamStop
	(*ServerMessage)(nil), // 4: astra.v1.ServerMessage
	(*StreamStarted)(nil), // 5: astra.v1.StreamStarted
	(*Error)(nil),         // 6: astra.v1.Error
}
var file_astra_v1_astra_proto_depIdxs = []int32{
	1, // 0: astra.v1.ClientMessage.stream_start:type_name -> astra.v1.StreamStart
	2, // 1: astra.v1.ClientMessage.audio_frame:type_name -> astra.v1.AudioFrame
	3, // 2: astra.v1.ClientMessage.stream_stop:type_name -> astra.v1.StreamStop
	5, // 3: astra.v1.ServerMessage.stream_started:type_name -> astra.v1.StreamStarted
	6, // 4: astra.v1.ServerMessage.error:type_name -> astra.v1.Error
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_astra_v1_astra_proto_init() }
func file_astra_v1_astra_proto_init() {
	if File_astra_v1_astra_proto != nil {
		return
	}
	file_astra_v1_astra_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_StreamStart)(nil),
		(*ClientMessage_AudioFrame)(nil),
		(*ClientMessage_StreamStop)(nil),
	}
	file_astra_v1_astra_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_StreamStarted)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astra_v1_astra_proto_rawDesc), len(file_astra_v1_astra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_astra_v1_astra_proto_goTypes,
		DependencyIndexes: file_astra_v1_astra_proto_depIdxs,
		MessageInfos:      file_astra_v1_astra_proto_msgTypes,
	}.Build()
	File_astra_v1_astra_proto = out.File
	file_astra_v1_astra_proto_goTypes = nil
	file_astra_v1_astra_proto_depIdxs = nil
}
