# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astra/v1/astra.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'astra/v1/astra.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61stra/v1/astra.proto\x12\x08\x61stra.v1\"\x9f\x01\n\rClientMessage\x12-\n\x0cstream_start\x18\x01 \x01(\x0b\x32\x15.astra.v1.StreamStartH\x00\x12+\n\x0b\x61udio_frame\x18\x02 \x01(\x0b\x32\x14.astra.v1.AudioFrameH\x00\x12+\n\x0bstream_stop\x18\x03 \x01(\x0b\x32\x14.astra.v1.StreamStopH\x00\x42\x05\n\x03msg\"k\n\x0bStreamStart\x12\x16\n\x0esample_rate_hz\x18\x01 \x01(\r\x12\x10\n\x08\x63hannels\x18\x02 \x01(\r\x12\x17\n\x0f\x62its_per_sample\x18\x03 \x01(\r\x12\x19\n\x11\x66rame_duration_ms\x18\x04 \x01(\r\"&\n\nAudioFrame\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x0b\n\x03pcm\x18\x02 \x01(\x0c\"\x0c\n\nStreamStop\"k\n\rServerMessage\x12\x31\n\x0estream_started\x18\x01 \x01(\x0b\x32\x17.astra.v1.StreamStartedH\x00\x12 \n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0f.astra.v1.ErrorH\x00\x42\x05\n\x03msg\"\"\n\rStreamStarted\x12\x11\n\tstream_id\x18\x01 \x01(\t\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\tB5Z3github.com/arnav/astra/services/backend/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astra.v1.astra_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/arnav/astra/services/backend/internal/pb'
  _globals['_CLIENTMESSAGE']._serialized_start=35
  _globals['_CLIENTMESSAGE']._serialized_end=194
  _globals['_STREAMSTART']._serialized_start=196
  _globals['_STREAMSTART']._serialized_end=303
  _globals['_AUDIOFRAME']._serialized_start=305
  _globals['_AUDIOFRAME']._serialized_end=343
  _globals['_STREAMSTOP']._serialized_start=345
  _globals['_STREAMSTOP']._serialized_end=357
  _globals['_SERVERMESSAGE']._serialized_start=359
  _globals['_SERVERMESSAGE']._serialized_end=466
  _globals['_STREAMSTARTED']._serialized_start=468
  _globals['_STREAMSTARTED']._serialized_end=502
  _globals['_ERROR']._serialized_start=504
  _globals['_ERROR']._serialized_end=542
# @@protoc_insertion_point(module_scope)
