// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: astra/v1/tts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	UtteranceId   uint64                 `protobuf:"varint,2,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_astra_v1_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_astra_v1_tts_proto_rawDescGZIP(), []int{0}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

type SynthesizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SynthesizeResponse_AudioStart
	//	*SynthesizeResponse_AudioChunk
	Msg           isSynthesizeResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_astra_v1_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_astra_v1_tts_proto_rawDescGZIP(), []int{1}
}

func (x *SynthesizeResponse) GetMsg() isSynthesizeResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SynthesizeResponse) GetAudioStart() *AudioStart {
	if x != nil {
		if x, ok := x.Msg.(*SynthesizeResponse_AudioStart); ok {
			return x.AudioStart
		}
	}
	return nil
}

func (x *SynthesizeResponse) GetAudioChunk() *TtsAudioChunk {
	if x != nil {
		if x, ok := x.Msg.(*SynthesizeResponse_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

type isSynthesizeResponse_Msg interface {
	isSynthesizeResponse_Msg()
}

type SynthesizeResponse_AudioStart struct {
	AudioStart *AudioStart `protobuf:"bytes,1,opt,name=audio_start,json=audioStart,proto3,oneof"`
}

type SynthesizeResponse_AudioChunk struct {
	AudioChunk *TtsAudioChunk `protobuf:"bytes,2,opt,name=audio_chunk,json=audioChunk,proto3,oneof"`
}

func (*SynthesizeResponse_AudioStart) isSynthesizeResponse_Msg() {}

func (*SynthesizeResponse_AudioChunk) isSynthesizeResponse_Msg() {}

type AudioStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRateHz  uint32                 `protobuf:"varint,1,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioStart) Reset() {
	*x = AudioStart{}
	mi := &file_astra_v1_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStart) ProtoMessage() {}

func (x *AudioStart) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStart.ProtoReflect.Descriptor instead.
func (*AudioStart) Descriptor() ([]byte, []int) {
	return file_astra_v1_tts_proto_rawDescGZIP(), []int{2}
}

func (x *AudioStart) GetSampleRateHz() uint32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

type TtsAudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcm           []byte                 `protobuf:"bytes,1,opt,name=pcm,proto3" json:"pcm,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsAudioChunk) Reset() {
	*x = TtsAudioChunk{}
	mi := &file_astra_v1_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsAudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsAudioChunk) ProtoMessage() {}

func (x *TtsAudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsAudioChunk.ProtoReflect.Descriptor instead.
func (*TtsAudioChunk) Descriptor() ([]byte, []int) {
	return file_astra_v1_tts_proto_rawDescGZIP(), []int{3}
}

func (x *TtsAudioChunk) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

func (x *TtsAudioChunk) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_astra_v1_tts_proto protoreflect.FileDescriptor

const file_astra_v1_tts_proto_rawDesc = "" +
	"\n" +
	"\x12astra/v1/tts.proto\x12\bastra.v1\"J\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12!\n" +
	"\futterance_id\x18\x02 \x01(\x04R\vutteranceId\"\x90\x01\n" +
	"\x12SynthesizeResponse\x127\n" +
	"\vaudio_start\x18\x01 \x01(\v2\x14.astra.v1.AudioStartH\x00R\n" +
	"audioStart\x12:\n" +
	"\vaudio_chunk\x18\x02 \x01(\v2\x17.astra.v1.TtsAudioChunkH\x00R\n" +
	"audioChunkB\x05\n" +
	"\x03msg\"2\n" +
	"\n" +
	"AudioStart\x12$\n" +
	"\x0esample_rate_hz\x18\x01 \x01(\rR\fsampleRateHz\"3\n" +
	"\rTtsAudioChunk\x12\x10\n" +
	"\x03pcm\x18\x01 \x01(\fR\x03pcm\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq2N\n" +
	"\x03TTS\x12G\n" +
	"\n" +
	"Synthesize\x12\x1b.astra.v1.SynthesizeRequest\x1a\x1c.astra.v1.SynthesizeResponseB9Z7github.com/arnav/astra/services/backend/internal/tts/pbb\x06proto3"

var (
	file_astra_v1_tts_proto_rawDescOnce sync.Once
	file_astra_v1_tts_proto_rawDescData []byte
)

func file_astra_v1_tts_proto_rawDescGZIP() []byte {
	file_astra_v1_tts_proto_rawDescOnce.Do(func() {
		file_astra_v1_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astra_v1_tts_proto_rawDesc), len(file_astra_v1_tts_proto_rawDesc)))
	})
	return file_astra_v1_tts_proto_rawDescData
}

var file_astra_v1_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_astra_v1_tts_proto_goTypes = []any{
	(*SynthesizeRequest)(nil),  // 0: astra.v1.SynthesizeRequest
	(*SynthesizeResponse)(nil), // 1: astra.v1.SynthesizeResponse
	(*AudioStart)(nil),         // 2: astra.v1.AudioStart
	(*TtsAudioChunk)(nil),      // 3: astra.v1.TtsAudioChunk
}
var file_astra_v1_tts_proto_depIdxs = []int32{
	2, // 0: astra.v1.SynthesizeResponse.audio_start:type_name -> astra.v1.AudioStart
	3, // 1: astra.v1.SynthesizeResponse.audio_chunk:type_name -> astra.v1.TtsAudioChunk
	0, // 2: astra.v1.TTS.Synthesize:input_type -> astra.v1.SynthesizeRequest
	1, // 3: astra.v1.TTS.Synthesize:output_type -> astra.v1.SynthesizeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_astra_v1_tts_proto_init() }
func file_astra_v1_tts_proto_init() {
	if File_astra_v1_tts_proto != nil {
		return
	}
	file_astra_v1_tts_proto_msgTypes[1].OneofWrappers = []any{
		(*SynthesizeResponse_AudioStart)(nil),
		(*SynthesizeResponse_AudioChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astra_v1_tts_proto_rawDesc), len(file_astra_v1_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astra_v1_tts_proto_goTypes,
		DependencyIndexes: file_astra_v1_tts_proto_depIdxs,
		MessageInfos:      file_astra_v1_tts_proto_msgTypes,
	}.Build()
	File_astra_v1_tts_proto = out.File
	file_astra_v1_tts_proto_goTypes = nil
	file_astra_v1_tts_proto_depIdxs = nil
}
