# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: astra/v1/tts.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'astra/v1/tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61stra/v1/tts.proto\x12\x08\x61stra.v1\"7\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0cutterance_id\x18\x02 \x01(\x04\"x\n\x12SynthesizeResponse\x12+\n\x0b\x61udio_start\x18\x01 \x01(\x0b\x32\x14.astra.v1.AudioStartH\x00\x12.\n\x0b\x61udio_chunk\x18\x02 \x01(\x0b\x32\x17.astra.v1.TtsAudioChunkH\x00\x42\x05\n\x03msg\"$\n\nAudioStart\x12\x16\n\x0esample_rate_hz\x18\x01 \x01(\r\")\n\rTtsAudioChunk\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x32N\n\x03TTS\x12G\n\nSynthesize\x12\x1b.astra.v1.SynthesizeRequest\x1a\x1c.astra.v1.SynthesizeResponseB9Z7github.com/arnav/astra/services/backend/internal/tts/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'astra.v1.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/arnav/astra/services/backend/internal/tts/pb'
  _globals['_SYNTHESIZEREQUEST']._serialized_start=32
  _globals['_SYNTHESIZEREQUEST']._serialized_end=87
  _globals['_SYNTHESIZERESPONSE']._serialized_start=89
  _globals['_SYNTHESIZERESPONSE']._serialized_end=209
  _globals['_AUDIOSTART']._serialized_start=211
  _globals['_AUDIOSTART']._serialized_end=247
  _globals['_TTSAUDIOCHUNK']._serialized_start=249
  _globals['_TTSAUDIOCHUNK']._serialized_end=290
  _globals['_TTS']._serialized_start=292
  _globals['_TTS']._serialized_end=370
# @@protoc_insertion_point(module_scope)
