// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: astra/v1/asr.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TranscribeRequest_Config
	//	*TranscribeRequest_Chunk
	Payload       isTranscribeRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_astra_v1_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_astra_v1_asr_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetPayload() isTranscribeRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TranscribeRequest) GetConfig() *StreamConfig {
	if x != nil {
		if x, ok := x.Payload.(*TranscribeRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *TranscribeRequest) GetChunk() *AudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*TranscribeRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isTranscribeRequest_Payload interface {
	isTranscribeRequest_Payload()
}

type TranscribeRequest_Config struct {
	Config *StreamConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type TranscribeRequest_Chunk struct {
	Chunk *AudioChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*TranscribeRequest_Config) isTranscribeRequest_Payload() {}

func (*TranscribeRequest_Chunk) isTranscribeRequest_Payload() {}

type StreamConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UtteranceId   uint64                 `protobuf:"varint,1,opt,name=utterance_id,json=utteranceId,proto3" json:"utterance_id,omitempty"`
	SampleRateHz  uint32                 `protobuf:"varint,2,opt,name=sample_rate_hz,json=sampleRateHz,proto3" json:"sample_rate_hz,omitempty"`
	Channels      uint32                 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	BitsPerSample uint32                 `protobuf:"varint,4,opt,name=bits_per_sample,json=bitsPerSample,proto3" json:"bits_per_sample,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfig) Reset() {
	*x = StreamConfig{}
	mi := &file_astra_v1_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfig) ProtoMessage() {}

func (x *StreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfig.ProtoReflect.Descriptor instead.
func (*StreamConfig) Descriptor() ([]byte, []int) {
	return file_astra_v1_asr_proto_rawDescGZIP(), []int{1}
}

func (x *StreamConfig) GetUtteranceId() uint64 {
	if x != nil {
		return x.UtteranceId
	}
	return 0
}

func (x *StreamConfig) GetSampleRateHz() uint32 {
	if x != nil {
		return x.SampleRateHz
	}
	return 0
}

func (x *StreamConfig) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *StreamConfig) GetBitsPerSample() uint32 {
	if x != nil {
		return x.BitsPerSample
	}
	return 0
}

func (x *StreamConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcm           []byte                 `protobuf:"bytes,1,opt,name=pcm,proto3" json:"pcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_astra_v1_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_astra_v1_asr_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

type TranscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_astra_v1_asr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astra_v1_asr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_astra_v1_asr_proto_rawDescGZIP(), []int{3}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_astra_v1_asr_proto protoreflect.FileDescriptor

const file_astra_v1_asr_proto_rawDesc = "" +
	"\n" +
	"\x12astra/v1/asr.proto\x12\bastra.v1\"~\n" +
	"\x11TranscribeRequest\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x16.astra.v1.StreamConfigH\x00R\x06config\x12,\n" +
	"\x05chunk\x18\x02 \x01(\v2\x14.astra.v1.AudioChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"\xcd\x01\n" +
	"\fStreamConfig\x12!\n" +
	"\futterance_id\x18\x01 \x01(\x04R\vutteranceId\x12$\n" +
	"\x0esample_rate_hz\x18\x02 \x01(\rR\fsampleRateHz\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\rR\bchannels\x12&\n" +
	"\x0fbits_per_sample\x18\x04 \x01(\rR\rbitsPerSample\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\"\x1e\n" +
	"\n" +
	"AudioChunk\x12\x10\n" +
	"\x03pcm\x18\x01 \x01(\fR\x03pcm\"C\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal2X\n" +
	"\x03ASR\x12Q\n" +
	"\x10StreamTranscribe\x12\x1b.astra.v1.TranscribeRequest\x1a\x1c.astra.v1.TranscribeResponse(\x010\x01B9Z7github.com/arnav/astra/services/backend/internal/asr/pbb\x06proto3"

var (
	file_astra_v1_asr_proto_rawDescOnce sync.Once
	file_astra_v1_asr_proto_rawDescData []byte
)

func file_astra_v1_asr_proto_rawDescGZIP() []byte {
	file_astra_v1_asr_proto_rawDescOnce.Do(func() {
		file_astra_v1_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astra_v1_asr_proto_rawDesc), len(file_astra_v1_asr_proto_rawDesc)))
	})
	return file_astra_v1_asr_proto_rawDescData
}

var file_astra_v1_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_astra_v1_asr_proto_goTypes = []any{
	(*TranscribeRequest)(nil),  // 0: astra.v1.TranscribeRequest
	(*StreamConfig)(nil),       // 1: astra.v1.StreamConfig
	(*AudioChunk)(nil),         // 2: astra.v1.AudioChunk
	(*TranscribeResponse)(nil), // 3: astra.v1.TranscribeResponse
}
var file_astra_v1_asr_proto_depIdxs = []int32{
	1, // 0: astra.v1.TranscribeRequest.config:type_name -> astra.v1.StreamConfig
	2, // 1: astra.v1.TranscribeRequest.chunk:type_name -> astra.v1.AudioChunk
	0, // 2: astra.v1.ASR.StreamTranscribe:input_type -> astra.v1.TranscribeRequest
	3, // 3: astra.v1.ASR.StreamTranscribe:output_type -> astra.v1.TranscribeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_astra_v1_asr_proto_init() }
func file_astra_v1_asr_proto_init() {
	if File_astra_v1_asr_proto != nil {
		return
	}
	file_astra_v1_asr_proto_msgTypes[0].OneofWrappers = []any{
		(*TranscribeRequest_Config)(nil),
		(*TranscribeRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astra_v1_asr_proto_rawDesc), len(file_astra_v1_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astra_v1_asr_proto_goTypes,
		DependencyIndexes: file_astra_v1_asr_proto_depIdxs,
		MessageInfos:      file_astra_v1_asr_proto_msgTypes,
	}.Build()
	File_astra_v1_asr_proto = out.File
	file_astra_v1_asr_proto_goTypes = nil
	file_astra_v1_asr_proto_depIdxs = nil
}
